name: inventory_app
description: "Inventory Management Application with offline-first approach."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Appwrite SDK for backend integration
  appwrite: ^13.0.0
  
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2
  
  # Local Storage for offline-first approach
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  
  # Network and API
  dio: ^5.4.1
  connectivity_plus: ^5.0.2
  json_annotation: ^4.8.1
  
  # Barcode scanning
  mobile_scanner: ^3.5.6
  qr_flutter: ^4.1.0
  
  # UI
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  lottie: ^3.1.0
  
  # Reporting and charts
  fl_chart: ^0.66.2
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Utils
  logger: ^2.0.2+1
  dartz: ^0.10.1
  rxdart: ^0.27.7
  uuid: ^4.3.3
  flutter_barcode_scanner: ^2.0.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
