version: '3.8'
services:
  mysql:
    image: mysql:lts
    container_name: mysql-latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - '3308:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
